DEBUG 2021-02-12 09:07:46.235 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-12 09:07:46.236 UTC: 	 Running on: Linux lxplus758.cern.ch 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-12 09:07:46.236 UTC: 	 Executing command: 'status'
DEBUG 2021-02-12 09:07:46.237 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/achhetri/.crab3
ERROR 2021-02-12 09:07:46.245 UTC: 	 Error: crab_Tprime_v5_NANo_AOD_106X/crab_TT_to_SemiLeptonic/ is not a valid CRAB project directory.
ERROR 2021-02-12 09:07:46.245 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_Tprime_v5_NANo_AOD_106X/crab_TT_to_SemiLeptonic/ is not a valid CRAB project directory.
INFO 2021-02-12 09:07:46.251 UTC: 	 Log file is /afs/cern.ch/work/a/achhetri/NANO_AOD/CMSSW_10_6_8/src/Phase_III_Analysis_with_NanoAOD/NANO_AOD_Analyzer/crab.log
